### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by zmoon** [barronh/pycmaq#2]
Seeing the timezone example in the readme, I was thinking it would be cool to include optional functionality to do this automatically, e.g. with [timezonefinder](https://github.com/jannikmi/timezonefinder). I would be down to try implementing this.

**Comment by barronh** [comment]
@zmoon - I do agree that we need clear methods to do common tasks. And, thank you for offering to implement! I am definitely looking for collaborators on this project.

For the specific timezone problem, I have a couple thoughts here.

1. I'm hesitant to create a dependency to timezonefinder this early in the development. Making it optional would definitely be important.

2. Depending on the resolution, grid cells may have several time zones. This is particularly true for the hemispheric polar stereographic domains. I typically use [NaturalEarth time zones](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_time_zones.zip) to create partial coverage by TZ and then assigned the cell-specific offset based on largest area overlap.

The example below gets a timezone for each grid cell. It is not super fast (~3min for hemi domain), but you should only have to do it once per domain. You would save the file for each domain in your project and rely upon it from there forward. Since many projects reuse domains, the optimization seems like a minor issue. 

```python
import pycmaq as pq
import shapefile
import pandas as pd
from shapely.geometry import shape

# https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_time_zones.zip
tzpath = 'ne_10m_time_zones.shp'
gdpath = 'GRIDDESC'

gf = pq.open_dataset(gdpath, engine='pseudonetcdf', backend_kwargs=dict(format='griddesc', GDNAM='108NHEMI2'))

tzshpf = shapefile.Reader(tzpath)
fldnames = [v[0] for v in tzshpf.fields[1:]]
attrdf = pd.DataFrame.from_records(tzshpf.iterRecords(), columns=fldnames)
tzkeys = []
for zoneval, rows in attrdf.groupby(['zone']):
    print(zoneval, end=',')
    shapes = [shape(tzshpf.shape(i)) for i in rows.index]
    gfrac = gf.cmaq.gridfraction(shapes=shapes, srcproj=4326)
    tzkey = f'TZ_{zoneval:.2f}'
    gf[tzkey] = gf['DUMMY'] * 0 + gfrac  
    tzkeys.append(tzkey)

print()

tzfrac = pq.xr.concat([gf[tzkey] for tzkey in tzkeys], dim='TSTEP')
gf['UTC_OFFSET'] = gf['DUMMY'] * 0 + pq.np.array([tzkey[3:] for tzkey in tzkeys], dtype='f')[tzfrac.argmax('TSTEP')]
# Visualize the result
gf['UTC_OFFSET'][0, 0].plot.pcolormesh()
# Save the result.
gf.attrs['SDATE'] = 1970001
gf[['UTC_OFFSET']].cmaq.to_ioapi('UTCOFFSET_108NHEMI2.nc')
```

Thoughts?

**Comment by zmoon** [comment]
A good point about the grid cells, it seems like timezonefinder only looks up point values. Looking up the grid cell center I would think (assuming reasonably high resolution) would usually give the same result as the maximum overlap zone, but that's not guaranteed.

I think this looks nice, and some room to optimize somewhat using the longitudes. I like the idea of providing a function to read the `GRIDDESC` and create a `UTCOFFSET.nc` that can provide an input for the `lst_*` functions. It would be a bit more complicated than this if you want to go from local standard time to local time though (accounting for daylight savings).

**Comment by barronh** [comment]
> I like the idea of providing a function to read the GRIDDESC and create a UTCOFFSET.nc

Good idea! I've added a new function `attr_from_shapefile` that has the ability to add any numeric attribute as a grid cell value. Currently, it can use grid centroids value, largest area fraction value, or area weighted average value. Obviously, the centroids are faster (~1min for the 35k cells in 108NHEMI2 compared to ~3.5min largest area overlap). The area weighted average would produce weird time zones near the dateline -- but that's a choice one could make

I'm going to clean this up before pushing to github. Probably later today.

```python
import pycmaq as pq

cmaqpath = '...'
tzpath = '...'
qf = pq.open_dataset(cmaqpath)
tz = qf.cmaq.attr_from_shapefile(tzpath, key='zone', srcproj=4326, method='centroid', units='hours from UTC', verbose=1)
qf['UTC_OFFSET'] = tz
# Save the result.
qf.cmaq.to_ioapi('UTCOFFSET.nc', overwrite=True)
```

> some room to optimize somewhat using the longitudes.

Can you be more specific? The current approach uses an STRtree to rapidly identify only the grid cells relevant to each polygon. This implicitly uses both lat and lon (after spatial subsetting, and converting to grid space). What optimization are you proposing?

**Comment by zmoon** [comment]
> Can you be more specific? The current approach uses an STRtree to rapidly identify only the grid cells relevant to each polygon. This implicitly uses both lat and lon (after spatial subsetting, and converting to grid space). What optimization are you proposing?

Ah ok, I hadn't looked closely at `gridfraction_frompoly`. That sounds better than what I was thinking.

> Good idea! I've added a new function `attr_from_shapefile` ...

Nice!

> I am definitely looking for collaborators on this project.

I am interested in helping out and learning more about CMAQ data.
